### ISSUE TITLE
get installation id fails with `ERR_OSSL_PEM_NO_START_LINE`

### ISSUE THREAD

**Issue by Raboo** [chriskinsman/github-action-dashboard#1]
Hi

I'm trying to run node getinstallationid.js and get the following error

```
Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:110:29)
    at Object.sign (/github-action-dashboard/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/github-action-dashboard/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/github-action-dashboard/node_modules/jsonwebtoken/sign.js:204:16)
    at getToken (/github-action-dashboard/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)
    at Object.githubAppJwt (/github-action-dashboard/node_modules/universal-github-app-jwt/dist-node/index.js:35:23)
    at getAppAuthentication (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:19:57)
    at hook (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:395:15)
    at /github-action-dashboard/node_modules/@octokit/plugin-request-log/dist-node/index.js:18:12
    at /github-action-dashboard/node_modules/before-after-hook/lib/register.js:25:15 {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

I did base64 encode the private key with `base64 -w0` (i.e. one line).
Any ideas on what I might be doing wrong?

**Comment by Raboo** [comment]
Actually it seems you can get the Installation ID from GitHub UI.
Just go to Settings -> Installed GitHub Apps -> Configure (the action dasboard). Then in the URL, the digits after last slash is your Installation ID.

**Comment by chriskinsman** [comment]
That is a great tip!  Thanks!

**Comment by Raboo** [comment]
getinstallationid.js still doesn't work which was the main reason I opened this issue. The tip is just a different way to get the installation id.

**Comment by thanakijwanavit** [comment]
have you figured out why its not working?

**Comment by thanakijwanavit** [comment]
i have the same problem too

**Comment by thanakijwanavit** [comment]
> Actually it seems you can get the Installation ID from GitHub UI.
> Just go to Settings -> Installed GitHub Apps -> Configure (the action dasboard). Then in the URL, the digits after last slash is your Installation ID.

this works

**Comment by chriskinsman** [comment]
Fixed and added your tip...
