### ISSUE TITLE
errors attempting to start up the container 

### ISSUE THREAD

**Issue by mx1010** [chriskinsman/github-action-dashboard#20]
Hello! I'm interested in trying out your dashboard for tracking actions use on enterprise server but I'm having a bit of trouble getting your Docker image started-up. Each time I try to run the container, I get the following message, or the container doesn't start as expected. Any ideas on what might be causing this ?

First attempt, container doesn't start.

```
$ docker -D run --rm -td -p 8080:8080 --env GITHUB_USERNAME=admin --env GITHUB_APPID=2 --env GITHUB_APP_PRIVATEKEY=XXXXXXXXXX --env GITHUB_APP_CLIENTID=Iv1.86a09b1296xxxxx --env GITHUB_APP_CLIENTSECRET=XXXXXXXXX --env GITHUB_APP_INSTALLATIONID=1 ghcr.io/chriskinsman/github-action-dashboard:edge node index.js
$ 54d560156bc506f77ba0499c00d7682cb28dbf70fa708f6fdced604ebac00d15
$ docker container ls
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

Second attempt removing the detached and clean-up flags, container throws error about missing modules.

```
$ docker run -p 8084:8084 --env GITHUB_USERNAME=admin --env GITHUB_APPID=2 --env GITHUB_APP_PRIVATEKEY=XXXXXXXXXX --env GITHUB_APP_CLIENTID=Iv1.86a09b1296xxxxxx --env GITHUB_APP_CLIENTSECRET=XXXXXXXXXX --env GITHUB_APP_INSTALLATIONID=1 ghcr.io/chriskinsman/github-action-dashboard:edge node index.js
Error on startup
Error: Cannot find module './actions'
Require stack:
- /github-action-dashboard/configure.js
- /github-action-dashboard/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/github-action-dashboard/configure.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/github-action-dashboard/configure.js',
    '/github-action-dashboard/index.js'
  ]
}
```

**Comment by chriskinsman** [comment]
Will take a look this evening. Have you tried a released version vs edge?

**Comment by chriskinsman** [comment]
So looks :latest or :1.5.0 is working.  

Checking into why the issues with edge.

**Comment by chriskinsman** [comment]
This should now be fixed on edge as well as dropping a 1.6.0 release. 

Sorry you got caught up in this. My refactoring while adding tests missed adding actions.js to the dockerfile.  

Should be all good now.  Thanks for opening the issue.

**Comment by mx1010** [comment]
👋  thank you for the prompt fix 💖

**Comment by mx1010** [comment]
Tried again and getting the same errors. Maybe I am doing something wrong, does this require a specific version of Docker and/or host OS? I'm currently running Docker 4.5.0 (74594) on MacOS Monterey 12.2.1.

```
(base) ➜  github-action-dashboard git:(main) docker run -p 8084:8084 --env GITHUB_USERNAME=admin --env GITHUB_APPID=2 --env GITHUB_APP_PRIVATEKEY=xxxxxx --env GITHUB_APP_CLIENTID=Iv1.86a09b1296b64e15 --env GITHUB_APP_CLIENTSECRET=xxxxxx --env GITHUB_APP_INSTALLATIONID=1 ghcr.io/chriskinsman/github-action-dashboard:edge node index.js
Error on startup
Error: Cannot find module './actions'
Require stack:
- /github-action-dashboard/configure.js
- /github-action-dashboard/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/github-action-dashboard/configure.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/github-action-dashboard/configure.js',
    '/github-action-dashboard/index.js'
  ]
}
(base) ➜  github-action-dashboard git:(main) docker -D run --rm -td -p 8084:8084 --env GITHUB_USERNAME=admin --env GITHUB_APPID=2 --env GITHUB_APP_PRIVATEKEY=xxxxxx --env GITHUB_APP_CLIENTID=Iv1.86a09b1296b64e15 --env GITHUB_APP_CLIENTSECRET=xxxxxx --env GITHUB_APP_INSTALLATIONID=1 ghcr.io/chriskinsman/github-action-dashboard:edge node index.js
524cf4586d54df89f237dde0dc23d7817a7884b24e81b6915041df3a929ec746
(base) ➜  github-action-dashboard git:(main)
```

Stripped all the vars and options and tried again.

```
(base) ➜  github-action-dashboard git:(main) docker -D run ghcr.io/chriskinsman/github-action-dashboard:edge node index.js
Error on startup
Error: Cannot find module './actions'
Require stack:
- /github-action-dashboard/configure.js
- /github-action-dashboard/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/github-action-dashboard/configure.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/github-action-dashboard/configure.js',
    '/github-action-dashboard/index.js'
  ]
}
DEBU[0000] [hijack] End of stdout
```

**Comment by mx1010** [comment]
Also, unable to re-open this issue.

**Comment by chriskinsman** [comment]
In case you have a cached edge container try this:

```
docker run -p 8084:8084 --env GITHUB_USERNAME=admin --env GITHUB_APPID=2 --env GITHUB_APP_PRIVATEKEY=xxxxxx --env GITHUB_APP_CLIENTID=Iv1.86a09b1296b64e15 --env GITHUB_APP_CLIENTSECRET=xxxxxx --env GITHUB_APP_INSTALLATIONID=1 ghcr.io/chriskinsman/github-action-dashboard:1.6.0 node index.js
```

**Comment by chriskinsman** [comment]
@mx1010 any luck?
