### ISSUE TITLE
PEM routines error after starting docker container

### ISSUE THREAD

**Issue by mx1010** [chriskinsman/github-action-dashboard#22]
👋 hi - I've since started over and now I'm getting a different error message regarding the private key I'm using on the app.

```
Error getting repos Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/github-action-dashboard/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/github-action-dashboard/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/github-action-dashboard/node_modules/jsonwebtoken/sign.js:204:16)
    at getToken (/github-action-dashboard/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)
    at Object.githubAppJwt (/github-action-dashboard/node_modules/universal-github-app-jwt/dist-node/index.js:35:23)
    at getAppAuthentication (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:110:59)
    at getInstallationAuthentication (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:269:35)
    at async hook (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:449:7)
    at async Job.doExecute (/github-action-dashboard/node_modules/bottleneck/light.js:405:18) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

I'm running Docker on Debian Buster, and I'd added all the env vars in via CLI manually prior to running, including copying the key over using ` GITHUB_APP_PRIVATEKEY="KEY-DATA"` and then issued the command as follows.

```
docker run -p 8080:8080 --env GITHUB_USERNAME=mx1010 --env GITHUB_APP_PRIVATEKEY="$GITHUB_APP_PRIVATEKEY" --env GITHUB_APPID="$GITHUB_APPID" --env GITHUB_APP_INSTALLATIONID="$GITHUB_APP_INSTALLATIONID" ghcr.io/chriskinsman/github-action-dashboard:1.6.0 node index.js
```

Any idea why it might be throwing this error? I've triple checked the app's private key using an online ssl checker.

**Comment by mike-jm** [comment]
Try base64 encoding the pem file:
`base64 -w0 < action-dashboard.pem > pem.base64`

**Comment by chriskinsman** [comment]
I was going to suggest something similar.  Thanks @mike-jm

**Comment by chriskinsman** [comment]
Haven't heard anything since the base64 suggestion

**Comment by carlos-tapasco** [comment]
> Try base64 encoding the pem file: `base64 -w0 < action-dashboard.pem > pem.base64`

Thanks to this thread I solve my problem. In Mac the option **-w0** is not supported. You must to use "**-b 0**" instead if you need.

`base64 -b 0 < private-key.pem > private-key.pem.base64`

More details in https://stackoverflow.com/questions/46463027/base64-doesnt-have-w-option-in-mac
