### ISSUE TITLE
Facing issue in getting installation ID

### ISSUE THREAD

**Issue by jkumar19** [chriskinsman/github-action-dashboard#4]
Hi chriskinsman ,

I was trying this code for dashboard and facing issue in getting the installation ID. I think I am missing something.

This is the error message:

Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:110:29)
    at Object.sign (/github-action-dashboard/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/github-action-dashboard/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/github-action-dashboard/node_modules/jsonwebtoken/sign.js:204:16)
    at getToken (/github-action-dashboard/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)
    at Object.githubAppJwt (/github-action-dashboard/node_modules/universal-github-app-jwt/dist-node/index.js:35:23)
    at getAppAuthentication (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:19:57)
    at hook (/github-action-dashboard/node_modules/@octokit/auth-app/dist-node/index.js:395:15)
    at /github-action-dashboard/node_modules/@octokit/plugin-request-log/dist-node/index.js:18:12
    at /github-action-dashboard/node_modules/before-after-hook/lib/register.js:25:15 {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'

I have generated the private key by following the steps you have mentioned in the screenshot. Can you please assist with this?

Thanks

**Comment by jkumar19** [comment]
This is fixed now. Closing this issue.
